# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret',
            field=models.TextField(max_length=250),
        ),
    ]
