# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0005_auto_20170302_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='like',
        ),
    ]
