# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 20:36
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0006_remove_secret_like'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='secret',
            managers=[
                ('secretManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
