# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0007_auto_20170302_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='like',
            field=models.ManyToManyField(related_name='liked', to='secrets.User'),
        ),
    ]
